Add jdk12 runner docker image
intuit/unmazedboot pull request #7
Opened 2019-10-24 21:50 UTC by dheeraj-tripathi

### Requirements

Add JDK12 runner docker image

2019-10-27 08:06 UTC, marcellodesales requested changes
@dheeraj-tripathi can you add the output of the test cases? Make sure it works so..

2019-10-27 09:20 UTC, dheeraj-tripathi commented
@marcellodesales Attached the logs for docker build and running the saamples
[run_samples.txt](https://github.com/intuit/unmazedboot/files/3775674/run_samples.txt)
[build_images.txt](https://github.com/intuit/unmazedboot/files/3775675/build_images.txt)

2019-10-30 01:04 UTC, marcellodesales commented
@dheeraj-tripathi I meant in the PR comments plain :) so anyone can see without downloading

2019-10-30 01:30 UTC, dheeraj-tripathi commented
Output for build images - 

`docker-compose build --pull`
Building builder-gradle4.10.2-jdk8-slim
Step 1/24 : ARG UNMAZEDBOOT_INTERNAL_BASE_IMAGE
Step 2/24 : FROM ${UNMAZEDBOOT_INTERNAL_BASE_IMAGE}
4.10.2-jdk8-slim: Pulling from library/gradle
Digest: sha256:14c8737471ace6f378a2e7fea7cf5b7ec45d5068da116b22e632c649cc12294b
Status: Image is up to date for gradle:4.10.2-jdk8-slim
 ---> ab2034020db7
Step 3/24 : USER root
 ---> Using cache
 ---> 8eb2cfbd8663
Step 4/24 : ARG UNMAZEDBOOT_INTERNAL_DEPENDENCIES
 ---> Using cache
 ---> 2a8334b3ce01
Step 5/24 : RUN sh -c "${UNMAZEDBOOT_INTERNAL_DEPENDENCIES}"
 ---> Using cache
 ---> 72c6366aecc2
Step 6/24 : ONBUILD ARG BUILDER_BINARY_DEPENDENCIES
 ---> Using cache
 ---> 107cbff3a569
Step 7/24 : ONBUILD RUN sh -c "${BUILDER_BINARY_DEPENDENCIES:-echo installing-no-builder-dependencies}"
 ---> Using cache
 ---> 293a9f911b3f
Step 8/24 : ONBUILD ARG UNMAZEDBOOT_BUILDER_GRADLE_BUILD_CMD
 ---> Using cache
 ---> 8d9119304bcd
Step 9/24 : ONBUILD ARG UNMAZEDBOOT_BUILDER_PACKAGE_EXTENSION
 ---> Using cache
 ---> 4565de9233d8
Step 10/24 : ONBUILD ENV UNMAZEDBOOT_BUILDER_PACKAGE_EXTENSION=${UNMAZEDBOOT_BUILDER_PACKAGE_EXTENSION}
 ---> Using cache
 ---> c4f660e458c3
Step 11/24 : ONBUILD ARG UNMAZEDBOOT_BUILDER_DIR
 ---> Using cache
 ---> e4220b040009
Step 12/24 : ONBUILD ENV UNMAZEDBOOT_BUILDER_DIR=${UNMAZEDBOOT_BUILDER_DIR}
 ---> Using cache
 ---> 8bf3fac26e16
Step 13/24 : WORKDIR /app/
 ---> Using cache
 ---> 5ac265250ca6
Step 14/24 : ONBUILD COPY ./build.gradle build.gradle
 ---> Using cache
 ---> b766b487a461
Step 15/24 : ONBUILD COPY ./settings.gradle settings.gradle
 ---> Using cache
 ---> e1d704d0a3a3
Step 16/24 : ONBUILD COPY ./src src/
 ---> Using cache
 ---> c1593150859c
Step 17/24 : ONBUILD RUN echo "Executing UNMAZEDBOOT_BUILDER_GRADLE_BUILD_CMD='${UNMAZEDBOOT_BUILDER_GRADLE_BUILD_CMD}'"
 ---> Using cache
 ---> fd678a57aa9c
Step 18/24 : ONBUILD RUN ${UNMAZEDBOOT_BUILDER_GRADLE_BUILD_CMD}
 ---> Using cache
 ---> 5903231e525f
Step 19/24 : ONBUILD RUN echo "Built artifacts at /app/${UNMAZEDBOOT_BUILDER_DIR} and looking for package .${UNMAZEDBOOT_BUILDER_PACKAGE_EXTENSION}"
 ---> Using cache
 ---> 06b17b703947
Step 20/24 : ONBUILD RUN find . -name "/app/${UNMAZEDBOOT_BUILDER_DIR}/*.${UNMAZEDBOOT_BUILDER_PACKAGE_EXTENSION}"
 ---> Using cache
 ---> f6eff64d9339
Step 21/24 : ONBUILD RUN echo "Renaming the executable ${UNMAZEDBOOT_BUILDER_PACKAGE_EXTENSION} to the runtime dir"
 ---> Using cache
 ---> cee3e986973c
Step 22/24 : ONBUILD RUN mkdir /runtime/ &&             find /app/${UNMAZEDBOOT_BUILDER_DIR} -name "*.${UNMAZEDBOOT_BUILDER_PACKAGE_EXTENSION}" ! -name "*sources*" ! -name "*javadoc*" -exec cp -t /runtime {} + &&             mv /runtime/*.${UNMAZEDBOOT_BUILDER_PACKAGE_EXTENSION} /runtime/server.jar
 ---> Using cache
 ---> 29b0ee250e13
Step 23/24 : ONBUILD RUN echo "Contents for built /runtime/server.jar"
 ---> Using cache
 ---> 4ed299fc80a6
Step 24/24 : ONBUILD RUN echo "jar -tf /runtime/server.jar"
 ---> Using cache
 ---> c997757225f5

Successfully built c997757225f5
Successfully tagged intuit/unmazedboot-builder-gradle:4.10.2-jdk8-slim-0.5.0
Building builder-gradle4.10.2-jdk8-alpine
Step 1/24 : ARG UNMAZEDBOOT_INTERNAL_BASE_IMAGE
Step 2/24 : FROM ${UNMAZEDBOOT_INTERNAL_BASE_IMAGE}
4.10.2-jdk8-alpine: Pulling from library/gradle
Digest: sha256:4097cf52fd95cbefc306299cb037614a27c76fc2f7531bee473a3769a670a7db
Status: Image is up to date for gradle:4.10.2-jdk8-alpine
 ---> e7e9b26b266b
Step 3/24 : USER root
 ---> Using cache
 ---> 6d566b12299d
Step 4/24 : ARG UNMAZEDBOOT_INTERNAL_DEPENDENCIES
 ---> Using cache
 ---> f95c0f907a78
Step 5/24 : RUN sh -c "${UNMAZEDBOOT_INTERNAL_DEPENDENCIES}"
 ---> Using cache
 ---> 3d281abb4823
Step 6/24 : ONBUILD ARG BUILDER_BINARY_DEPENDENCIES
 ---> Using cache
 ---> 456db3f47a26
Step 7/24 : ONBUILD RUN sh -c "${BUILDER_BINARY_DEPENDENCIES:-echo installing-no-builder-dependencies}"
 ---> Using cache
 ---> 5f406b738b80
Step 8/24 : ONBUILD ARG UNMAZEDBOOT_BUILDER_GRADLE_BUILD_CMD
 ---> Using cache
 ---> 045499a3a085
Step 9/24 : ONBUILD ARG UNMAZEDBOOT_BUILDER_PACKAGE_EXTENSION
 ---> Using cache
 ---> fa23a27d918a
Step 10/24 : ONBUILD ENV UNMAZEDBOOT_BUILDER_PACKAGE_EXTENSION=${UNMAZEDBOOT_BUILDER_PACKAGE_EXTENSION}
 ---> Using cache
 ---> cd39de82ffbb
Step 11/24 : ONBUILD ARG UNMAZEDBOOT_BUILDER_DIR
 ---> Using cache
 ---> dfb8188355cf
Step 12/24 : ONBUILD ENV UNMAZEDBOOT_BUILDER_DIR=${UNMAZEDBOOT_BUILDER_DIR}
 ---> Using cache
 ---> cbac9e272fc9
Step 13/24 : WORKDIR /app/
 ---> Using cache
 ---> 0ea4b403749f
Step 14/24 : ONBUILD COPY ./build.gradle build.gradle
 ---> Using cache
 ---> 79929a61c411
Step 15/24 : ONBUILD COPY ./settings.gradle settings.gradle
 ---> Using cache
 ---> 441a1ad6f28d
Step 16/24 : ONBUILD COPY ./src src/
 ---> Using cache
 ---> b2e15c24085f
Step 17/24 : ONBUILD RUN echo "Executing UNMAZEDBOOT_BUILDER_GRADLE_BUILD_CMD='${UNMAZEDBOOT_BUILDER_GRADLE_BUILD_CMD}'"
 ---> Using cache
 ---> 801b1fb012c5
Step 18/24 : ONBUILD RUN ${UNMAZEDBOOT_BUILDER_GRADLE_BUILD_CMD}
 ---> Using cache
 ---> 4da98d1475fb
Step 19/24 : ONBUILD RUN echo "Built artifacts at /app/${UNMAZEDBOOT_BUILDER_DIR} and looking for package .${UNMAZEDBOOT_BUILDER_PACKAGE_EXTENSION}"
 ---> Using cache
 ---> bdc11d6e2962
Step 20/24 : ONBUILD RUN find . -name "/app/${UNMAZEDBOOT_BUILDER_DIR}/*.${UNMAZEDBOOT_BUILDER_PACKAGE_EXTENSION}"
 ---> Using cache
 ---> bc458ee169ef
Step 21/24 : ONBUILD RUN echo "Renaming the executable ${UNMAZEDBOOT_BUILDER_PACKAGE_EXTENSION} to the runtime dir"
 ---> Using cache
 ---> 144c5d19227b
Step 22/24 : ONBUILD RUN mkdir /runtime/ &&             find /app/${UNMAZEDBOOT_BUILDER_DIR} -name "*.${UNMAZEDBOOT_BUILDER_PACKAGE_EXTENSION}" ! -name "*sources*" ! -name "*javadoc*" -exec cp -t /runtime {} + &&             mv /runtime/*.${UNMAZEDBOOT_BUILDER_PACKAGE_EXTENSION} /runtime/server.jar
 ---> Using cache
 ---> 5c0812b4078d
Step 23/24 : ONBUILD RUN echo "Contents for built /runtime/server.jar"
 ---> Using cache
 ---> 697a019ab1e2
Step 24/24 : ONBUILD RUN echo "jar -tf /runtime/server.jar"
 ---> Using cache
 ---> 4757edfe1dcf

Successfully built 4757edfe1dcf
Successfully tagged intuit/unmazedboot-builder-gradle:4.10.2-jdk8-alpine-0.5.0
Building builder-gradle5.0.0-jdk8-slim
Step 1/24 : ARG UNMAZEDBOOT_INTERNAL_BASE_IMAGE
Step 2/24 : FROM ${UNMAZEDBOOT_INTERNAL_BASE_IMAGE}
5.0.0-jdk8-slim: Pulling from library/gradle
Digest: sha256:ac20c1340b220e69a978a33f5bbee68b95cc11329132042bee271beebeed2ff0
Status: Image is up to date for gradle:5.0.0-jdk8-slim
 ---> 063266435f3c
Step 3/24 : USER root
 ---> Using cache
 ---> c0f64b6a7a75
Step 4/24 : ARG UNMAZEDBOOT_INTERNAL_DEPENDENCIES
 ---> Using cache
 ---> 9c31265606ef
Step 5/24 : RUN sh -c "${UNMAZEDBOOT_INTERNAL_DEPENDENCIES}"
 ---> Using cache
 ---> 1680476f00bb
Step 6/24 : ONBUILD ARG BUILDER_BINARY_DEPENDENCIES
 ---> Using cache
 ---> 987189331ea0
Step 7/24 : ONBUILD RUN sh -c "${BUILDER_BINARY_DEPENDENCIES:-echo installing-no-builder-dependencies}"
 ---> Using cache
 ---> f35dabe9df2c
Step 8/24 : ONBUILD ARG UNMAZEDBOOT_BUILDER_GRADLE_BUILD_CMD
 ---> Using cache
 ---> c6591bedf2b1
Step 9/24 : ONBUILD ARG UNMAZEDBOOT_BUILDER_PACKAGE_EXTENSION
 ---> Using cache
 ---> 735dcfdea261
Step 10/24 : ONBUILD ENV UNMAZEDBOOT_BUILDER_PACKAGE_EXTENSION=${UNMAZEDBOOT_BUILDER_PACKAGE_EXTENSION}
 ---> Using cache
 ---> ca6c33cdbff9
Step 11/24 : ONBUILD ARG UNMAZEDBOOT_BUILDER_DIR
 ---> Using cache
 ---> d1752eabb944
Step 12/24 : ONBUILD ENV UNMAZEDBOOT_BUILDER_DIR=${UNMAZEDBOOT_BUILDER_DIR}
 ---> Using cache
 ---> 658fb4e7e35d
Step 13/24 : WORKDIR /app/
 ---> Using cache
 ---> 7763b9932252
Step 14/24 : ONBUILD COPY ./build.gradle build.gradle
 ---> Using cache
 ---> c9bc1a20a22b
Step 15/24 : ONBUILD COPY ./settings.gradle settings.gradle
 ---> Using cache
 ---> 65063bc44bea
Step 16/24 : ONBUILD COPY ./src src/
 ---> Using cache
 ---> af24592d746f
Step 17/24 : ONBUILD RUN echo "Executing UNMAZEDBOOT_BUILDER_GRADLE_BUILD_CMD='${UNMAZEDBOOT_BUIL [...]

2019-10-30 01:32 UTC, dheeraj-tripathi commented
Run all the samples,

`docker-compose -f docker-compose-samples.yml up`

Starting unmazedboot_sample-jdk11-x-jre-custom-12_1                    ... done
Starting unmazedboot_samples-gradle-kotlin-jdk8-jre8_1                 ... done
Starting unmazedboot_samples-gradle-java-jdk8-x-jre-custom-11-alpine_1 ... done
Starting unmazedboot_samples-gradle-java-jdk8-x-jre-custom-11-centos_1 ... done
Starting unmazedboot_samples-gradle-java-jdk8-x-jre-custom-11-debian_1 ... done
Starting unmazedboot_samples-maven-java-jdk11-x-jre-custom-11_1        ... done
Starting unmazedboot_sample-gradle-java-jre8_1                         ... done
Attaching to unmazedboot_samples-gradle-kotlin-jdk8-jre8_1, unmazedboot_sample-jdk11-x-jre-custom-12_1, unmazedboot_samples-gradle-java-jdk8-x-jre-custom-11-alpine_1, unmazedboot_samples-maven-java-jdk11-x-jre-custom-11_1, unmazedboot_samples-gradle-java-jdk8-x-jre-custom-11-centos_1, unmazedboot_samples-gradle-java-jdk8-x-jre-custom-11-debian_1, unmazedboot_sample-gradle-java-jre8_1
samples-gradle-kotlin-jdk8-jre8_1                  | 
samples-gradle-kotlin-jdk8-jre8_1                  | => Initializing SpringBoot Runner 'start.sh'
samples-gradle-kotlin-jdk8-jre8_1                  | 
samples-gradle-kotlin-jdk8-jre8_1                  | ########## Running init scripts at '/runtime/init'
samples-gradle-kotlin-jdk8-jre8_1                  | 
sample-jdk11-x-jre-custom-12_1                     | 
sample-jdk11-x-jre-custom-12_1                     | => Initializing SpringBoot Runner 'start.sh'
samples-gradle-java-jdk8-x-jre-custom-11-alpine_1  | 
samples-gradle-java-jdk8-x-jre-custom-11-alpine_1  | => Initializing SpringBoot Runner 'start.sh'
samples-maven-java-jdk11-x-jre-custom-11_1         | 
samples-maven-java-jdk11-x-jre-custom-11_1         | => Initializing SpringBoot Runner 'start.sh'
samples-maven-java-jdk11-x-jre-custom-11_1         | 
samples-maven-java-jdk11-x-jre-custom-11_1         | ########## Running init scripts at '/runtime/init'
samples-maven-java-jdk11-x-jre-custom-11_1         | 
samples-gradle-kotlin-jdk8-jre8_1                  | 
samples-gradle-kotlin-jdk8-jre8_1                  | ########## Processing source hooks at '/runtime/sources'
samples-gradle-kotlin-jdk8-jre8_1                  | 
samples-gradle-java-jdk8-x-jre-custom-11-alpine_1  | 
samples-gradle-java-jdk8-x-jre-custom-11-alpine_1  | ########## Running init scripts at '/runtime/init'
samples-gradle-java-jdk8-x-jre-custom-11-alpine_1  | 
sample-gradle-java-jre8_1                          | 
sample-gradle-java-jre8_1                          | => Initializing SpringBoot Runner 'start.sh'
samples-gradle-java-jdk8-x-jre-custom-11-alpine_1  | 
samples-gradle-java-jdk8-x-jre-custom-11-alpine_1  | ########## Processing source hooks at '/runtime/sources'
samples-gradle-java-jdk8-x-jre-custom-11-alpine_1  | 
sample-gradle-java-jre8_1                          | 
sample-jdk11-x-jre-custom-12_1                     | 
sample-jdk11-x-jre-custom-12_1                     | ########## Running init scripts at '/runtime/init'
sample-jdk11-x-jre-custom-12_1                     | 
samples-maven-java-jdk11-x-jre-custom-11_1         | 
samples-gradle-kotlin-jdk8-jre8_1                  | [1] source /runtime/sources/springboot.sh
samples-gradle-java-jdk8-x-jre-custom-11-centos_1  | 
samples-gradle-java-jdk8-x-jre-custom-11-centos_1  | => Initializing SpringBoot Runner 'start.sh'
samples-gradle-java-jdk8-x-jre-custom-11-debian_1  | 
samples-gradle-java-jdk8-x-jre-custom-11-debian_1  | => Initializing SpringBoot Runner 'start.sh'
sample-jdk11-x-jre-custom-12_1                     | 
sample-jdk11-x-jre-custom-12_1                     | ########## Processing source hooks at '/runtime/sources'
sample-jdk11-x-jre-custom-12_1                     | 
sample-gradle-java-jre8_1                          | ########## Running init scripts at '/runtime/init'
samples-maven-java-jdk11-x-jre-custom-11_1         | ########## Processing source hooks at '/runtime/sources'
samples-maven-java-jdk11-x-jre-custom-11_1         | 
samples-gradle-java-jdk8-x-jre-custom-11-alpine_1  | [1] source /runtime/sources/springboot.sh
samples-maven-java-jdk11-x-jre-custom-11_1         | [1] source /runtime/sources/springboot.sh
samples-maven-java-jdk11-x-jre-custom-11_1         | 
samples-gradle-java-jdk8-x-jre-custom-11-debian_1  | 
samples-gradle-java-jdk8-x-jre-custom-11-debian_1  | ########## Running init scripts at '/runtime/init'
samples-gradle-java-jdk8-x-jre-custom-11-debian_1  | 
sample-jdk11-x-jre-custom-12_1                     | [1] source /runtime/sources/springboot.sh
samples-gradle-java-jdk8-x-jre-custom-11-centos_1  | 
samples-gradle-java-jdk8-x-jre-custom-11-centos_1  | ########## Running init scripts at '/runtime/init'
samples-gradle-java-jdk8-x-jre-custom-11-centos_1  | 
sample-gradle-java-jre8_1                          | 
samples-gradle-kotlin-jdk8-jre8_1                  | 
samples-gradle-kotlin-jdk8-jre8_1                  | => Processing JAVA_OPTS hooks at /runtime/java-opts
samples-gradle-kotlin-jdk8-jre8_1                  | 
samples-maven-java-jdk11-x-jre-custom-11_1         | => Processing JAVA_OPTS hooks at /runtime/java-opts
samples-maven-java-jdk11-x-jre-custom-11_1         | 
samples-gradle-java-jdk8-x-jre-custom-11-debian_1  | 
samples-gradle-java-jdk8-x-jre-custom-11-debian_1  | ########## Processing source hooks at '/runtime/sources'
samples-gradle-java-jdk8-x-jre-custom-11-debian_1  | 
sample-gradle-java-jre8_1                          | 
sample-jdk11-x-jre-custom-12_1                     | 
sample-jdk11-x-jre-custom-12_1                     | => Processing JAVA_OPTS hooks at /runtime/java-opts
sample-jdk11-x-jre-custom-12_1                     | 
samples-gradle-java-jdk8-x-jre-custom-11-alpine_1  | 
samples-gradle-java-jdk8-x-jre-custom-11-alpine_1  | => Processing JAVA_OPTS hooks at /runtime/java-opts
samples-gradle-java-jdk8-x-jre-custom-11-alpine_1  | 
samples-gradle-kotlin-jdk8-jre8_1                  | [1] JAVA_OPTS << ./java-opts/docker.opt
sample-jdk11-x-jre-custom-12_1                     | [1] JAVA_OPTS << ./java-opts/vminfo.opt
samples-maven-java-jdk11-x-jre-custom-11_1         | [1] JAVA_OPTS << ./java-opts/flight-recorder.opt
samples-gradle-java-jdk8-x-jre-custom-11-alpine_1  | [1] JAVA_OPTS << ./java-opts/vminfo.opt
samples-gradle-java-jdk8-x-jre-custom-11-alpine_1  | [2] JAVA_OPTS << ./java-opts/docker.opt
samples-gradle-kotlin-jdk8-jre8_1                  | [2] JAVA_OPTS << ./java-opts/springboot.opt
samples-gradle-java-jdk8-x-jre-custom-11-debian_1  | [1] source /runtime/sources/springboot.sh
sample-gradle-java-jre8_1                          | ########## Processing source hooks at '/runtime/sources'
samples-maven-java-jdk11-x-jre-custom-11_1         | [2] JAVA_OPTS << ./java-opts/vminfo.opt
samples-gradle-java-jdk8-x-jre-custom-11-centos_1  | 
samples-gradle-java-jdk8-x-jre-custom-11-centos_1  | ########## Processing source hooks at '/runtime/sources'
samples-gradle-java-jdk8-x-jre-custom-11-centos_1  | 
samples-gradle-java-jdk8-x-jre-custom-11-alpine_1  | [3] JAVA_OPTS << ./java-opts/jdk-custom-debug.opt
sample-jdk11-x-jre-custom-12_1                     | [2] JAVA_OPTS << ./java-opts/docker.opt
samples-gradle-kotlin-jdk8-jre8_1                  | 
samples-gradle-kotlin-jdk8-jre8_1                  | Exporting and merging  JAVA_OPTS=-showversion -XshowSettings:vm  -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
samples-gradle-java-jdk8-x-jre-custom-11-debian_1  | 
samples-gradle-java-jdk8-x-jre-custom-11-debian_1  | => Processing JAVA_OPTS hooks at /runtime/java-opts
samples-gradle-java-jdk8-x-jre-custom-11-debian_1  | 
samples-maven-java-jdk11-x-jre-custom-11_1         | [3] JAVA_OPTS << ./java-opts/docker.opt
sample-jdk11-x-jre-custom-12_1                     | [3] JAVA_OPTS << ./java-opts/jdk-custom-debug.opt
samples-gradle-java-jdk8-x-jre-custom-11-alpine_1  | [4] JAVA_OPTS << ./java-opts/spri [...]

2019-10-30 01:34 UTC, dheeraj-tripathi commented
@marcellodesales pasted o/p above

2019-11-01 15:45 UTC, merged